apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    type: NodePort
    ports:
        - targetPort: 9000
          port: 9000
          nodePort: 30007
    selector:
        env: staging-app
