apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    type: NodePort
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30009
        - targetPort: 443
          port: 443
          nodePort: 30010
    selector:
        env: staging-nginx
