apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: app-pvc
    labels:
        name: apppvc1
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
