apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nginx-pvc
    labels:
        name: nginxpvc1
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
