apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis-pvc
    labels:
        name: redispvc1
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
